services:
  mysql_database:
    image: mysql:latest
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql/data

volumes:
  db_data:
